language: java
addons:
  sonarcloud:
    organization: inveasy
script:
- mvn clean install sonar:sonar -Dsonar.login=${SONAR_LOGIN} -B -V
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
  provider: releases
  api_key:
    secure: LE5DrNNMgkDDQVd3mkWFGrCRdF37qMAoMf0GKeDe4y/5kDTmf3hC9Rfv++vWfbAo5uXybmKG+Y+5JoH5BBcD1VYzg8H0EnTIjJivdZyooKPAYsfGUH4cLML5UAOKuy0uTjZuejV/P3WOQeUJu4MBGmCiyTDPvMzerTaaXSSzZJDkmbpRpMFxYMnk96sI663tTAFPO8TusCnXD9sVCfPjcCACZbJuMVdO+BXqgny6PplN4uIf9yxwEQsoz2ZGLxbBTN0N4ZMaD6U3iAHMOqkoi31gLv+hz5suvOmZL8gy5dkmQox6TuW7Zj0nBFqnXihvgBXxqTL0dko6n+Q68IvDTl3tE3Szw1mxZ89yx2ct1D9yytbkZKEN0YELvau9jnmpkDLwZcVb41kyqzuw581nf/GZ3b0bbU1YYmGvJDWfQuP6t6Fy6HhoUrNDSupqnwUh09CCZMdTMiprEL4cnMcUQtxkEwpMe6HKmsMbxMZ/GKulNNxgSkavvyTNfxuhidMnoy5Q/fZaq6QhNwTT1v7vucAjXaoXA4eeIhLQQZimmdYcPSXQMcn2SFL9LEqiLb+aojFENHiv/zDoH2zUTCP+tJSw8gA2WHJtp8Q+7O6Wv1iv46/meqqHRiXFBSdVc5d97KXaj2y30g0UecGE4EpMCDbkoacZtWow4a7N5iJioqc=
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    tags: true
